- name: Incus server setup for Debian/Ubuntu
  hosts: all
  tasks:
    - name: Flush handlers
      meta: flush_handlers
  roles:

    - role: sudo
      tags:
        - sudo
        - never

    - role: basic
      tags:
        - basic

    - role: tmpfs
      when:
        - ansible_os_family == "Debian"
      tags:
        - tmpfs

    - role: unsnap
      when:
        - ansible_distribution == "Ubuntu"
      tags:
        - unsnap

    - role: zram
      tags:
        - zram
        - never

    - role: incus
      tags:
        - incus
        - never

    - role: wireguard
      tags:
        - wireguard
        - never

    - role: reboot
      tags:
        - reboot
        - never

