config:
  core.https_address: 192.168.22.152:8443
networks: []
storage_pools:
  - config:
      source: /var/lib/incus/storage-pools/local
    description: ""
    name: local
    driver: btrfs
storage_volumes: []
profiles:
  - config: {}
    description: ""
    devices:
      root:
        path: /
        pool: local
        type: disk
    name: default
    project: default
projects: []
certificates: []
cluster:
  server_name: incus-ubuntu-test
  enabled: true
  member_config: []
  cluster_address: ""
  cluster_certificate: ""
  server_address: ""
  cluster_token: ""
  cluster_certificate_path: ""
