# main vars for pkg role

pkg_basic:
  present:
    - bash-completion
    - bat
    - bsdextrautils
    - btrfs-progs
    - byobu
    - command-not-found
    - curl
    - fd-find
    - fzf
    - git
    - htop
    - iperf3
    - jq
    - psmisc
    - python-is-python3
    - python3-debian # for Ansible deb822_repository module
    - ripgrep
    - tmux

  absent:
    - yq # python version

