# main tasks for incus role

- name: Import installation tasks
  import_tasks:
    file: install.yaml

- name: Import initialization tasks
  when: false
  import_tasks:
    file: init.yaml

- name: Import tuning tasks
  import_tasks:
    file: tuning.yaml

- name: Import user tasks
  import_tasks:
    file: user.yaml

